"""add ruid

Revision ID: 0b3b64c29686
Revises: 962a5d4af159
Create Date: 2025-02-16 20:55:16.019046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3b64c29686'
down_revision: Union[str, None] = '962a5d4af159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature_reading', sa.Column('ruid', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature_reading', 'ruid')
    # ### end Alembic commands ###
