"""add gas sensor and moisture

Revision ID: fe74e2c8b3bc
Revises: 0b3b64c29686
Create Date: 2025-03-23 17:36:47.851119

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe74e2c8b3bc"
down_revision: Union[str, None] = "0b3b64c29686"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temperature_reading",
        sa.Column("moisture", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.add_column(
        "temperature_reading",
        sa.Column("gas_level", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.drop_column("temperature_reading", "ruid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temperature_reading",
        sa.Column(
            "ruid",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("temperature_reading", "gas_level")
    op.drop_column("temperature_reading", "moisture")
    # ### end Alembic commands ###
